[package]
name = "palcalc"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
clap = { version = "4.5.9", features = ["derive"] }
image = "0.25.1"
rand = "0.8.5"
rayon = "1.10.0"
wild = "2.2.1"
